// Generated by CoffeeScript 1.7.1
(function() {
  var TEXT, TRM, assert, log;

  TEXT = require('./main');

  TRM = require('coffeenode-trm');

  log = TRM.log.bind(TRM);

  assert = require('assert');

  this.main = function() {
    return this.test_lines_splitting();
  };

  this.test_lines_splitting = function() {
    assert.deepEqual(TEXT.lines_of('helo world'), ['helo world']);
    assert.deepEqual(TEXT.lines_of('helo world\n'), ['helo world', '']);
    assert.deepEqual(TEXT.lines_of('helo world\nhowdy'), ['helo world', 'howdy']);
    assert.deepEqual(TEXT.lines_of('helo world\rhowdy'), ['helo world', 'howdy']);
    assert.deepEqual(TEXT.lines_of('helo world\r\nhowdy'), ['helo world', 'howdy']);
    assert.deepEqual(TEXT.lines_of('helo world\n\rhowdy'), ['helo world', '', 'howdy']);
    assert.deepEqual(TEXT.lines_of('\nhelo world\n\rhowdy'), ['', 'helo world', '', 'howdy']);
    return assert.deepEqual(TEXT.lines_of('a\u0085b\u2028c\u2029d'), ['a', 'b', 'c', 'd']);
  };

  this.main();

}).call(this);
